name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generate documentation
      run: cargo build --target-dir docs/
    - name: Publish documentation
      uses: EndBug/add-and-commit@v7
      with:
        add : 'docs/*'
        message: 'Creating Rust documentation'
        committer_name: GitHub Actions
        committer_email: actions@github.com
